version: 2
orbs:
  vulnerability-checker: whitesource/vulnerability-checker@19.10.1
jobs:
  build:
    docker:
      - image: circleci/node:12-buster
    steps:
      - checkout
      - run:
          name: Run Tests
          command: |
            npm run test
          when: always
      - setup_remote_docker:
          version: 18.06.0-ce
          when: always
      - run:
          name: Install docker
          command: |
            apt-get update --fix-missing
            apt-get install -y apt-transport-https ca-certificates software-properties-common
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
            apt-key fingerprint 0EBFCD88
            add-apt-repository \
              "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
              $(lsb_release -cs) \
              stable"
            apt-get update
            apt-get install -y docker-ce
            docker --version
          when: always
      - run:
          name: Build and push Docker image
          command: |
            docker build -t cph1c06/$IMAGE_NAME:$TAG .
      - run:
          name: "Start Service and Check That it’s Running"
          command: |
            docker run -d --name my-app cph1c06/$IMAGE_NAME:$TAG
            docker exec my-app curl --retry 10 --retry-connrefused http://localhost:4000
          when: always
      - run:
          command: |
            curl -LJO https://vulnerability-checker.s3.amazonaws.com/release/partner/CircleCI/wss-vulnerability-checker-201910-Top250-Top50-CircleCI.zip
            unzip wss-vulnerability-checker-201910-Top250-Top50-CircleCI.zip
            ./vulnerability-checker.sh -d <<parameters.directory>>
            mkdir -p /tmp/results
            cp VulnerabilityCheckerReport.html /tmp/results
            echo check artifacts for results
          when: always
